import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, EB_Garamond } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider"

const eb_garamond = EB_Garamond({
  subsets: ["latin"],
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter} antialiased bg-[#0e100f] text-[#fffce1]`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
        >
            {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
